name: eco_toss
description: A Flame game template built with Flutter.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ^3.0.0

dependencies:
  animations: ^2.0.11
  audioplayers: ^5.2.0
  cloud_firestore: ^4.15.3
  cupertino_icons: ^1.0.6
  firebase_core: ^2.25.3
  flame: ^1.14.0
  flame_audio: ^2.1.3
  flutter:
    sdk: flutter
  get_it: ^7.6.7
  go_router: ^12.1.0
  google_fonts: ^6.1.0
  injectable: ^2.3.2
  logging: ^1.2.0
  nes_ui: ^0.10.0
  package_info_plus: ^5.0.1
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  simple_icons: ^10.1.3
  store_redirect: ^2.0.1

dev_dependencies:
  build_runner: ^2.4.8
  flame_test: ^1.14.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.1
  test: ^1.24.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/dash/
    - assets/images/enemies/
    - assets/images/scenery/
    - assets/music/
    - assets/sfx/

  fonts:
    - family: Press Start 2P
      fonts:
        - asset: assets/fonts/Press_Start_2P/PressStart2P-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
