// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAqHOWr-6RYbC01jZGlOc_C4cikHelNpY',
    appId: '1:26615248153:web:77003e1de7a370a89b0188',
    messagingSenderId: '26615248153',
    projectId: 'eco-toss',
    authDomain: 'eco-toss.firebaseapp.com',
    storageBucket: 'eco-toss.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIOoirST1wvq0UobQ_a1gc4HqNiSS_160',
    appId: '1:26615248153:android:a7b363cecf5a7d6a9b0188',
    messagingSenderId: '26615248153',
    projectId: 'eco-toss',
    storageBucket: 'eco-toss.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4KCjrb8D0bLUw8XKc4oqejftRXj11Pzw',
    appId: '1:26615248153:ios:3982685d019f11de9b0188',
    messagingSenderId: '26615248153',
    projectId: 'eco-toss',
    storageBucket: 'eco-toss.appspot.com',
    iosBundleId: 'com.justinkek.ecoToss',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4KCjrb8D0bLUw8XKc4oqejftRXj11Pzw',
    appId: '1:26615248153:ios:3982685d019f11de9b0188',
    messagingSenderId: '26615248153',
    projectId: 'eco-toss',
    storageBucket: 'eco-toss.appspot.com',
    iosBundleId: 'com.justinkek.ecoToss',
  );
}
